language: php
php:
- 5.4
- 5.5
- 5.6
install:
- travis_retry composer self-update
- travis_retry composer install
- if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.4" ] ; then echo "no" | pecl install apcu-4.0.7 ; fi
- phpenv config-add tests/config/$TRAVIS_PHP_VERSION.ini
before_script:
- mkdir -p applications bundles cache
- phpenv rehash
script:
after_success:
cache:
  apt: true
  directories:
  - vendor
notifications:
  slack:
    secure: OwI7PtL9OGmGvwJ8SRObkTvl0cMQqRssLJ+fWwrAUQ4HW/CxAg95q0jPZ4YHmUk6eFTp23HtYrV62icVUiw0dmbGOnsKBPKW5fMs8+rXTXcKi4lu5sP8lsak8ORBLcp75pagiMrviMS6nvAJO/l0U7XMGGGHJjbfyLa5bRkXdRo=
